#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import time
import logging
import configpi
import json

from louie import dispatcher
from datetime import datetime
from flask import jsonify
from collections import OrderedDict

from openzwave.network import ZWaveNetwork
from openzwave.option import ZWaveOption

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('openzwave')

started = False
name = configpi.name



###########################################################################################################################
###########################################################################################################################
##########    Root parent backend class     ###############################################################################
###########################################################################################################################
###########################################################################################################################


class Backend():

    def __init__(self):

    ###################  instanciation de l'objet backend ########################################################


    ###### options needed for python openzwave library like config files path, logging,
        device = configpi.interface
        options = ZWaveOption(device, config_path="/home/pi/IoTLab/python-openzwave/openzwave/config", user_path=".", cmd_line="")
        options.set_log_file("OZW.log")
        options.set_append_log_file(False)
        options.set_console_output(False)
        options.set_save_log_level('Warning')
        options.set_logging(True)
        options.lock()

        # creation of the object network using the options entity already created
        self.network = ZWaveNetwork(options, autostart=False)

    ######   These dispatchers associate a method to a signal. the signals are generated by the library python-openzwave.
    ######   Once the signal is received. It's associated method is executed (see "_node_added" example below in "_network_started" method)
        dispatcher.connect(self._network_started, ZWaveNetwork.SIGNAL_NETWORK_STARTED)
        dispatcher.connect(self._network_ready, ZWaveNetwork.SIGNAL_NETWORK_READY)

    ###### backend object attributes
#        self.devices = OrderedDict()  ### will contain the list of nodes in the network
#        self.sensors = OrderedDict()  ### will contain the list of sensors (only) in the network
        self.node_added = False
        self.node_removed = False
        self.timestamps = {}          ### will contain the time of the last values' update for each sensor
        self.queryStages = {          ### the diffrent stages that a node object gets through before being ready
                "None"                  :  1, # Query process hasn't started for this node
                "ProtocolInfo"          :  2, # Retrieve protocol information
                "Probe"                 :  3, # Ping device to see if alive
                "WakeUp"                :  4, # Start wake up process if a sleeping node
                "ManufacturerSpecific1" :  5, # Retrieve manufacturer name and product ids if ProtocolInfo lets us
                "NodeInfo"              :  6, # Retrieve info about supported, controlled command classes
                "SecurityReport"        :  7, # Retrieve a list of Command Classes that require Security
                "ManufacturerSpecific2" :  8, # Retrieve manufacturer name and product ids
                "Versions"              :  9, # Retrieve version information
                "Instances"             : 10, # Retrieve information about multiple command class instances
                "Static"                : 11, # Retrieve static information (doesn't change)
                "Probe1"                : 12, # Ping a device upon starting with configuration
                "Associations"          : 13, # Retrieve information about associations
                "Neighbors"             : 14, # Retrieve node neighbor list
                "Session"               : 15, # Retrieve session information (changes infrequently)
                "Dynamic"               : 16, # Retrieve dynamic information (changes frequently)
                "Configuration"         : 17, # Retrieve configurable parameter information (only done on request)
                "Complete"              : 18  # Query process is completed for this node
        }

#######################################################################################################################
############# LAUNCH  #################################################################################################
#######################################################################################################################

    def _network_started(self, network):

    # executed once the software representation is started. the discovery of the network components has begun. they will be mapped into objects

        print("network started - %d nodes were found." % network.nodes_count)

    # these dispatchers associate a method to a signal. the signals are generated by the library python-openzwave.
    # a signal may contain a number of parameters that are passed to the method associated to the signal.
    # for exemple, the dispatcher below associates the signal "SIGNAL_NODE_ADDED" to the method "_node_added" that is implemented below (line 111).
    # the signal "SIGNAL_NODE_ADDED" transports two parameters which are the objects network and node.
    # once this signal is received, these two parameters will be passed to the method "_node_added" and the method will be executed.

        dispatcher.connect(self._node_added, ZWaveNetwork.SIGNAL_NODE_ADDED)
        dispatcher.connect(self._node_removed, ZWaveNetwork.SIGNAL_NODE_REMOVED)




    def _network_ready(self, network):

    # executed once the software representation is ready

        print("network : ready : %d nodes were found." % network.nodes_count)
        print("network : controller is : %s" % network.controller)
        dispatcher.connect(self._value_update, ZWaveNetwork.SIGNAL_VALUE)

    def _node_added(self, network, node):

    # executed when node is added to the software representation. it's executed after the method "_debug_node_new" (see below)

        print('node added: %s.' % node.node_id)
        self.timestamps["timestamp" + str(node.node_id)] = "None"
        self.node_added = True

    def _node_removed(self, network, node):

    # executed when node is removed from the software representation

        print('node removed: %s.' % node.name)
        self.node_removed = True


    def _value_update(self, network, node, value):

    # executed when a new value from a node is received

        print('Node %s: value update: %s is %s.' % (node.node_id, value.label, value.data))
        self.timestamps["timestamp" + str(node.node_id)] = int(time.time())




################################################################################################################
######################## START AND STOP THE SOFTWARE REPRESENTATION ############################################
################################################################################################################

    def start(self):

    # this method starts the software representation
        global started


        if started:
            print "Already started"
            return
        started = True
        self.network.start()
        print "Z-Wave Network Starting..."
        for i in range(0, 300):
            if self.network.state == self.network.STATE_READY:
                break
            else:
                time.sleep(1.0)
        if not self.network.is_ready:
            print "Network is not ready but continue anyway"
        print "------------------------------------------------------------"
        print "Nodes in network : %s" % self.network.nodes_count
        print "------------------------------------------------------------"

    def stop(self):

    # this method stops the software representation

        global started
        started = False
        print "Stopping Z-Wave Network... "
        self.network.stop()

    def reset(self):
        if self.network.nodes_count == 1:
            self.network.controller.hard_reset()
            return "Hard Reset Done"
        return "Cannot make Hard Reset while nodes included in network"




#########################################################################################################################
############## YOUR WORK STARTS HERE ####################################################################################
#########################################################################################################################
#########################################################################################################################




#######################################################################################################################
############# NETWORK #################################################################################################
#######################################################################################################################


    def network_info(self):

        #### COMPLETE THIS METHOD ##############
        result = {
            "home_id": self.network.home_id_str,
            "nodes": [self._node_as_obj(node) for i, node in self.network.nodes.items()]
        }

        return json.dumps(result)




#######################################################################################################################
############# NODES #################################################################################################
#######################################################################################################################

    def _node_as_obj(self, node):

        stage = node.getNodeQueryStage
        stagePercent = -1

        if stage in self.queryStages:
            stageNbr = self.queryStages[stage]
            stagePercent = (stageNbr/18.0) * 100

        return {
            "is_ready": node.isReady,
            "neighbours": len(node.neighbors),
            "node_id": node.node_id,
            "node_location": node.location,
            "node_name": node.name,
            "product_name": node.product_name,
            "query_stage": node.getNodeQueryStage,
            "query_stage_percent": stagePercent
        }


    def ordered_nodes_dict(self):

    # returns an ordered list of the network's nodes sorted by node's id

        return OrderedDict(sorted(self.network.nodes.items()))



    def addNode(self):

        #### COMPLETE THIS METHOD ##############
        ctrl = self.network.controller
        if not ctrl.begin_command_add_device():
            return "could not set the controller in exclusion mode" # TODO: error code

        if self.node_added: # TODO: should wait for 20s
            self.node_added = False
            ctrl.cancel_command()
            return "Node added successfully"

        ctrl.cancel_command()

        return "this method passes the controller to inclusion mode and gets it out of it after 20 seconds "



    def removeNode(self):

        #### COMPLETE THIS METHOD ##############

       return "this method passes the controller to exclusion mode and gets it out of it after 20 seconds "



    def get_nodes_list(self):
        #### COMPLETE THIS METHOD ##############
        return json.dumps([self._node_as_obj(node) for node in self.network.nodes.values()])




    def _set_field(self, n, field, value):
        if n in self.network.nodes.keys():
            node = self.network.nodes[n]
            node.set_field(field, value)
            return jsonify(node_id = n, value = node.to_dict()[field])

        return jsonify(error = "This node does not exist"), 400

    def set_node_name(self, n, value):
        return self._set_field(n, 'name', value)

    def set_node_location(self, n, value):
        return self._set_field(n, 'location', value)




    def get_node_location(self, n):
        #### COMPLETE THIS METHOD ##############
        if n in self.network.nodes.keys():
            node = self.network.nodes[n]
            return jsonify(node_id = node.node_id, location = node.location)
        return jsonify(error = "node not found"), 404



    def get_node_name(self, n):
        #### COMPLETE THIS METHOD ##############
        if n in self.network.nodes.keys():
            node = self.network.nodes[n]
            return jsonify(id = node.node_id, name = node.name)
        return jsonify(error = "node not found"), 404



    def get_neighbours_list(self, n):
        result = [self._node_as_obj(self.network.nodes[i]) for i in self.network.nodes[n].neighbors]
        return json.dumps(result)



    def set_node_config_parameter(self, n, param, value, size):

        #### COMPLETE THIS METHOD ##############

        return "this method sets a configuration parameter to a given value"



    def get_node_config_parameter(self, n, param):

        #### COMPLETE THIS METHOD ##############

     return "this method gets the value of a configuration parameter"



    def get_nodes_Configuration(self):

        #### COMPLETE THIS METHOD ##############

        return "this method returns a JSON that gives an overview of the network and it's nodes' configuration parameters (like the ID, Wake-up Interval, Group 1 Reports, Group 1 Interval ...)"



#######################################################################################################################
############# Multisensors #################################################################################################
#######################################################################################################################

class Backend_with_sensors(Backend):

    def get_sensors_list(self):
        #### COMPLETE THIS METHOD ##############
        sensors = [self._node_as_obj(node) for node in self.network.nodes.values() if node.node_id != self.network.controller.node_id]
        return json.dumps(sensors)



    def get_temperature(self, n):

        #### HERE'S AN EXAMPLE OF A METHOD THAT GETS THE TEMPERATURE OF A SPECIFIC SENSOR NODE ##############

        for node in self.network.nodes.itervalues():
            if node.node_id == n and node.isReady and n != 1 and "timestamp"+str(node.node_id) in self.timestamps:
                values = node.get_values(0x31, "User", "All", True, False)
                for value in values.itervalues():
                    if value.label == "Temperature":
                        val = round(value.data,1)
                #        if len(node.location) < 3:
                #            node.location = configpi.sensors[str(node.node_id)][:4]
                        return jsonify(controller = name, sensor = node.node_id, location = node.location, type = value.label.lower(), updateTime = self.timestamps["timestamp"+str(node.node_id)], value = val)
        return jsonify( error = "Node not ready or wrong sensor node !")



    def get_humidity(self, n):

         #### HERE'S AN EXAMPLE OF A METHOD THAT GETS THE HUMIDITY OF A SPECIFIC SENSOR NODE ##############

        for node in self.network.nodes.itervalues():
            if node.node_id == n and node.isReady and n != 1 and "timestamp"+str(node.node_id) in self.timestamps:
                values = node.get_values(0x31, "User", "All", True, False)
                for value in values.itervalues():
                    if value.label == "Relative Humidity":
                        val = int(value.data)
                 #       if len(node.location) < 3:
                 #           node.location = configpi.sensors[str(node.node_id)][:4]
                        return jsonify(controller = name, sensor = node.node_id, location = node.location, type = value.label.lower(), updateTime = self.timestamps["timestamp"+str(node.node_id)], value = val)

        return jsonify(error = "Node not ready or wrong sensor node !")


    def _find_sensor_value(self, n, label):
        if n == self.network.controller.node_id or not n in self.network.nodes.keys():
            return jsonify(error = "This node does not exist or is not a sensor node"), 400

        node = self.network.nodes[n]
        if not node.isReady or "timestamp"+str(node.node_id) not in self.timestamps:
            return jsonify(error = "This node is not ready"), 500

        values = [ v for v in node.get_values(0x31, "User", "All", True, False).values() if v.label == label ]

        if len(values) == 0:
            return jsonify(error = "This node does not have a " + label + " sensor"), 400

        return values[0], -1

    def get_luminance(self, n):
        
        value, status_code = self._find_sensor_value(n, 'Luminance')
        if status_code > 0:
            return value, status_code

        node = self.network.nodes[n]

        return jsonify(
            controller = name,
            sensor = node.node_id,
            location = node.location,
            type = value.label.lower(),
            updateTime = self.timestamps["timestamp"+str(node.node_id)],
            value = value.data)



    def get_motion(self, n):

        #### COMPLETE THIS METHOD ##############

        return "this method this method gets the motion measure of a specific sensor node"



    def get_battery(self, n):
        #### COMPLETE THIS METHOD ##############
        return "battery"



    def get_all_Measures(self, n):

        #### COMPLETE THIS METHOD ##############

        return "this method gets all the measures of a specific sensor node"



    def set_basic_nodes_configuration(self, Grp_interval, Grp_reports, Wakeup_interval):

        #### COMPLETE THIS METHOD ##############

        return "this method configures the nodes whit a specific configuration"







###########################################################################################################################
###########################################################################################################################
##################    Dimmers class     ##################################################################################
###########################################################################################################################
###########################################################################################################################

class Backend_with_dimmers(Backend):


    def __init__(self):
        Backend.__init__(self)



    def get_dimmers(self):

        #### COMPLETE THIS METHOD ##############

        return "this method returns the list of dimmers"



    def set_dimmer_level(self, n, level):

        #### COMPLETE THIS METHOD ##############

        return "this method sets a dimmer's brightness level of a specific node"



    def get_dimmer_level(self, n):

        #### COMPLETE THIS METHOD ##############

        return "this method gets a dimmer's brightness level of a specific node"






###########################################################################################################################
###########################################################################################################################
##########    Dimmers and multisensors class         ######################################## #############################
###########################################################################################################################
###########################################################################################################################

class Backend_with_dimmers_and_sensors(Backend_with_dimmers, Backend_with_sensors): # Cette classe sera utilise dans "flask-main"

    pass


